### ISSUE TITLE
ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is

### ISSUE THREAD

**Issue by mertkonrat** [nicolomantini/LinkedIn-Easy-Apply-Bot#101]
**Describe the bug**
I can log in successfully, but then I get this error:
:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is

**Screenshots**
![Capture](https://user-images.githubusercontent.com/19364945/185810004-b8e702bc-1bfe-4c32-90e0-d40f238b7f90.JPG)
https://prnt.sc/Y8_r5yjYYWYG

**Desktop (please complete the following information):**
Using:
 - Win 10
 - Browser: Chrome

**Comment by Chainging** [comment]
I got this problem too! May I ask how did you solved this situation?
