### ISSUE TITLE
no such element: Unable to locate element: {"method":"css selector","selector":".jobs-search-results"}

### ISSUE THREAD

**Issue by mrtknrt** [nicolomantini/LinkedIn-Easy-Apply-Bot#102]
**Describe the bug**
The bot logins to LinkedIn but never applies for jobs or even searches for the criteria not sure what is happening.

**Screenshots**
![image](https://user-images.githubusercontent.com/19364945/187188085-3b07faa2-db91-4f14-a111-ff0884e88a2a.png)

**Error Statement**
Message: no such element: Unable to locate element: {"method":"css selector","selector":".jobs-search-results-list"}
  (Session info: chrome=104.0.5112.102)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome

**To Reproduce**
Just run the bot and it gives the error message and doesn't apply for jobs.

**Comment by yunniiart** [comment]
Same issue~

**Comment by yunniiart** [comment]
I fixed it. Change jobs-search-results to jobs-search-results-list in the python file.

**Comment by yunniiart** [comment]
Hmm, weird. The only other thing I did in my own file was add some more sleep time and it did start working. There is a delay between the bot logging in and to when it actually applies to jobs, however. Mine sits on the page after searching for the jobs for a minute, but it does do it.

**Comment by kaushikslearning** [comment]
> Hmm, weird. The only other thing I did in my own file was add some more sleep time and it did start working. There is a delay between the bot logging in and to when it actually applies to jobs, however. Mine sits on the page after searching for the jobs for a minute, but it does do it.

Where exactly did you add the sleep time, can you please elaborate?

**Comment by ZaneBaylon** [comment]
I had this problem and fixed it independently, works for my setup. 

                scrollresults = self.browser.find_element(By.CLASS_NAME,
                    "jobs-search-results-list"
                )

Please note that you have to update selenium syntax to the newest version, between those two that was what was messing up my scrolling. Linkedin has been changing this area lately so keep an eye out!
