### ISSUE TITLE
Syntax Error in easyapplybot.py

### ISSUE THREAD

**Issue by aaronhouillon** [nicolomantini/LinkedIn-Easy-Apply-Bot#107]
Getting this error trying to run the script: 
```
line 206
    self.browser, jobs_per_page: int = self.next_jobs_page(position,
    ^^^^^^^^^^^^
SyntaxError: only single target (not tuple) can be annotated
```

**Comment by 21jujubees** [comment]
I'm also getting this error, figured it had something to do with what version of Python I was running, so I tried the latest version and still got this error.

**Comment by samilAyoub** [comment]
me too

**Comment by samilAyoub** [comment]
what python version you are using?

**Comment by 21jujubees** [comment]
Using 3.10.7

**Comment by MaxFritzhand** [comment]
Here is the fix:
OLD:
line 206
    self.browser, jobs_per_page: int = self.next_jobs_page(position,

NEW:
line 206
    self.browser, jobs_per_page = self.next_jobs_page(position,

I believe their is also another reference of this, so remove that as well and this issue should be resolved

**Comment by samilAyoub** [comment]
I think It would be better if we could know which python version is used

**Comment by MaxFritzhand** [comment]
I was using python3

**Comment by MaxFritzhand** [comment]
3.7.8

**Comment by aaronhouillon** [comment]
I'm using Python 3.10.6

**Comment by 21jujubees** [comment]
> Here is the fix: OLD: line 206 self.browser, jobs_per_page: int = self.next_jobs_page(position,
> 
> NEW: line 206 self.browser, jobs_per_page = self.next_jobs_page(position,
> 
> I believe their is also another reference of this, so remove that as well and this issue should be resolved

This worked for me, thank you! I also had to change line 70.

OLD:
def get_appliedIDs(self, filename) -> list | None:

NEW:
def get_appliedIDs(self, filename) -> list:

**Comment by aaronhouillon** [comment]
I've implemented these fixes, and the code will run, but now it's not applying to any jobs :( it just keeps sleeping and waiting while the LinkedIn jobs are pulled up on the screen.

**Comment by 21jujubees** [comment]
> I've implemented these fixes, and the code will run, but now it's not applying to any jobs :( it just keeps sleeping and waiting while the LinkedIn jobs are pulled up on the screen.

Yeah the same thing happens to me but at least I get to see it boot up, kinda lost as to where to go from here lol

**Comment by MaxFritzhand** [comment]
I can send you my revised version of the code snippet if that helps? How can I share it with you guys?

**Comment by octoshrimpy** [comment]
@MaxFritzhand just make a PR here with your changes, so we can see your fork. :smile:

**Comment by MaxFritzhand** [comment]
Have a look at my branch! Just added @octoshrimpy @21jujubees let me know if this helps. Just use this easyapplybot.py file and it should be good to go.

**Comment by jacobbaehr** [comment]
@MaxFritzhand Awesome job! If I want to specify jobs posted in the last 24 hours, do you know what changes I would have to make in your fork?

**Comment by jacobbaehr** [comment]
> @MaxFritzhand Awesome job! If I want to specify jobs posted in the last 24 hours, do you know what changes I would have to make in your fork?

I figured it out if anyone wants to know. Just change the url on line 406 to "https://www.linkedin.com/jobs/search/?f_LF=f_AL&f_TPR=r86400&keywords=" and it will specify jobs posted in the last 24 hours

**Comment by ZaneBaylon** [comment]
> @MaxFritzhand Awesome job! If I want to specify jobs posted in the last 24 hours, do you know what changes I would have to make in your fork?

I'm not farmiliar with Jacob's fork but in the original version that's specified in the csv management section on line 79

            df = df[df['timestamp'] > (datetime.now() - timedelta(days=2))]

Changing 'days=(# of days you want)' should work

**Comment by ZaneBaylon** [comment]
> I've implemented these fixes, and the code will run, but now it's not applying to any jobs :( it just keeps sleeping and waiting while the LinkedIn jobs are pulled up on the screen.

I had the same issue as well. LinkedIn has been changing the HTML lately and that's why your code cannot find the element. Change line 186 to:

                      './/a[@data-control-id]'

There may be some lingering issues finding the jobIDs, but this at least should allow your code to apply. Hope this helps!
