### ISSUE TITLE
Cannot log in after chrome pops up

### ISSUE THREAD

**Issue by mrtknrt** [nicolomantini/LinkedIn-Easy-Apply-Bot#111]
**Describe the bug**
Cannot log in after chrome pops up

**Screenshots**
![image](https://user-images.githubusercontent.com/19364945/197860269-54d62f52-6313-4fca-a24b-a92c2141be9a.png)

**Desktop (please complete the following information):**
 - Win10
 - Chrome
 - Latest version

**To Reproduce**
1. cmd on file
2. run py -3 easyapplybot.py

**Comment by alt888111** [comment]
I'm having similar issue, as well as this "executable_path has been deprecated" warning
tried in a condo environment and on windows with the same results, this seems to have something to do with selenium and webdriver_manager version compatibility 
![cmd_8tROqvxxs1](https://user-images.githubusercontent.com/48738846/197878610-96783b57-0af2-42ba-b90a-7bebf4192d30.png)
![powershell_FMvQA1cTfm](https://user-images.githubusercontent.com/48738846/197878617-2875fd8c-71b5-4fd1-983d-e94535c3bf10.png)

**Comment by mrtknrt** [comment]
i fgured it out the issue
