### ISSUE TITLE
The bot is not applying for the right job

### ISSUE THREAD

**Issue by ManuCiao10** [nicolomantini/LinkedIn-Easy-Apply-Bot#113]
The keyword are not working anymore, prob linkdein changed something with the search bar.
Plus now there are more questin even in the "easy apply", where the bot is not able to fill
<img width="1138" alt="Screenshot 2022-11-06 at 19 16 31" src="https://user-images.githubusercontent.com/89024276/200203545-8656c214-dc7c-40ad-bda1-fa2bac96ceda.png">

**Comment by avryxapps** [comment]
Yeah its also not picking the right location for me

**Comment by thdevine** [comment]
@ManuCiao10 post a screen shot of your .yaml file
