### ISSUE TITLE
Bot not running line 42 and 72 error. 

### ISSUE THREAD

**Issue by faran678** [nicolomantini/LinkedIn-Easy-Apply-Bot#114]
<img width="578" alt="Screen Shot 2022-11-07 at 11 41 24 AM" src="https://user-images.githubusercontent.com/44625575/200365780-e708b48c-f327-4f25-825b-c58e3d8cbd7f.png">

**Describe the bug**

**Screenshots**
If applicable, add screenshots of the LinkedIn page you are attempting to apply to. 

**Logs**
If applicable, attach your logs file found in `./logs/`

**Error Statement**
If applicable and not stated above, provide the error statement you are receiving. 

**Desktop (please complete the following information):**

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by avryxapps** [comment]
Also getting this problem.

**Comment by Neiljoshi97** [comment]
Same issue!

**Comment by faran678** [comment]
Does anyone know how we can fix this?

**Comment by faran678** [comment]
Can you attach a screenshot of the error?

**Comment by WananiAdib** [comment]
I fixed the issue by downloading Python 3.10 cause earlier version do not support '|' operator

**Comment by avryxapps** [comment]
Thanks, upgrading Python worked.

**Comment by faran678** [comment]
Same it worked
