### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by sophiezxf** [nicolomantini/LinkedIn-Easy-Apply-Bot#115]
python3 easyapplybot.py

I got this error:

/Users/xxx/Downloads/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py:22: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())
Traceback (most recent call last):
  File "/Users/xxxDownloads/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py", line 42, in <module>
    class EasyApplyBot:
  File "/Users/xxx/Downloads/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py", line 72, in EasyApplyBot
    def get_appliedIDs(self, filename) -> list | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by bhaskard** [comment]
@sophiezxf Add "from __future__ import annotations" to the top of the file

**Comment by zarigata** [comment]
im getting the same error, did not resolve at all

**Comment by PH13** [comment]
I fixed this error by having an up-to-date python 3.10. 

In case you are using conda it does not support 3.10 yet. You need to make a fresh environment and it should work. You can go to an older codebase of the easyapply app and it might just work out of the box on your version of python.
