### ISSUE TITLE
The bot can't exit out of applications

### ISSUE THREAD

**Issue by faran678** [nicolomantini/LinkedIn-Easy-Apply-Bot#119]
<img width="741" alt="Screenshot 2022-12-19 at 6 24 37 AM" src="https://user-images.githubusercontent.com/44625575/208415793-df384c48-72d0-4be2-8fff-542117599759.png">
<img width="905" alt="Screenshot 2022-12-19 at 6 25 35 AM" src="https://user-images.githubusercontent.com/44625575/208415795-5a83f300-971e-42f2-ad12-345cae5d4d38.png">

The bot can't exit out of applications, it seems like there is a new button for exiting applications. Any rec?

**Comment by PH13** [comment]
From my understanding, I don't think it's a new button to exit. 

I think the code is not recognizing the "Please enter a valid answer". Once the code sees this it should just open the URL to the next application. Doesn't even exit.

Probably has to do with line 376:

            error_locator = (By.CSS_SELECTOR,
                             "p[data-test-form-element-error-message='true']")

**Comment by faran678** [comment]
@PH13 I have line 376 correct same as what you have. What do you recommend I tried adding a dismiss button but the same issue continues.

**Comment by PH13** [comment]
@faran678 I have been tinkering and have still not found a solution. Having two problems right now. This and the choose resume dialogue. Trying to fix the choose resume dialogue first since that usually comes up first then I'll try this problem.

**Comment by faran678** [comment]
No worries, thanks for trying

**Comment by PH13** [comment]
Working on this now, found temp solution for resume selection.

**Comment by PH13** [comment]
Replace "p[data-test-form-element-error-message='true']" on line 332 and 377 with [aria-invalid='true'] and bot should work as it was designed to. It will discard the application and move to the next one.

**Comment by zadohu22** [comment]
completely delete line 375 and replace it with the following code. this fixes the form error :)

`error_locator = (By.ID,
                             "single-line-text-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-3403224438-77781877-numeric-error")`

**Comment by zadohu22** [comment]
replace line 375 with the following code. :)

`            error_locator = (By.CLASS_NAME,
                             "artdeco-inline-feedback__message")`

**Comment by faran678** [comment]
Works perfectly, thanks for the help. Good work guys
