### ISSUE TITLE
No such element: Unable to locate element

### ISSUE THREAD

**Issue by thdevine** [nicolomantini/LinkedIn-Easy-Apply-Bot#120]
Message: no such element: Unable to locate element:

I've ran this script many times, restarted, same issue. This is a fun script. Not sure why it's tanking.
![image](https://user-images.githubusercontent.com/79164883/208509857-a7b87f24-dd60-49e5-ac90-f2bd427a0601.png)

**Comment by PH13** [comment]
If that doesn't work try:

        input_field = self.browser.find_element("xpath", '//*[contains(concat( " ", @class, " " ), concat( " ", "artdeco-text-input--input", " " ))]')

**Comment by dimonoid** [comment]
Same issue, previous solutions don't work

**Comment by xConde** [comment]
try `input_field = self.browser.find_element(By.CSS_SELECTOR, "input.artdeco-text-input--input[type='text']")`
