### ISSUE TITLE
Does not automatically select resume

### ISSUE THREAD

**Issue by kuzae** [nicolomantini/LinkedIn-Easy-Apply-Bot#121]
Resume's aren't chosen when applying, Linkedin changed the ability to set default resume.

Bot prevention by LinkedIn renders the bot pretty useless outside of a couple job listing that doesn't require a resume to be selected.

You can get around this by uploading the resume every time, but chances are this will flag you as a bot as you will endlessly keep uploading new resumes every job listing.

**Comment by mohamed-sultan** [comment]
@kuzae /
https://www.linkedin.com/jobs/application-settings/
go for the above link then remove all resume only keep the one u need

**Comment by kuzae** [comment]
> @kuzae / https://www.linkedin.com/jobs/application-settings/ go for the above link then remove all resume only keep the one u need

That doesnt' change anything. Linkedin removed the ability to preset a default resume.
![image](https://user-images.githubusercontent.com/39451132/209444436-185f1b85-5f02-42b5-929b-ae4475759949.png)
Retroactively removing all the resumes after the script upload it 200 times is not a reasonable thing to do.

**Comment by PH13** [comment]
I added the following to line 389 and 390 and it will choose the top resume on this list if the dialogue appears.

                    resume_select = self.browser.find_element("xpath", '/html/body/div[3]/div/div/div[2]/div/div[2]/form/div/div/div/div[1]/div/div[2]/div[1]/div[2]/button[1]')
                    resume_select.click()

**Comment by PH13** [comment]
Also comment out 390 to 400

                    # input_buttons = self.browser.find_elements(upload_locator[0],
                    #                                            upload_locator[1])
                    # for input_button in input_buttons:
                    #     parent = input_button.find_element(By.XPATH, "..")
                    #     sibling = parent.find_element(By.XPATH, "preceding-sibling::*")
                    #     grandparent = sibling.find_element(By.XPATH, "..")
                    #     for key in self.uploads.keys():
                    #         sibling_text = sibling.text
                    #         gparent_text = grandparent.text
                    #         if key.lower() in sibling_text.lower() or key in gparent_text.lower():
                    #             input_button.send_keys(self.uploads[key])

**Comment by kuzae** [comment]
I've created a fork that resolves this issue, as well as a couple of other issues that rose from linked in updating their UI.
