### ISSUE TITLE
Doesn't' run at all...

### ISSUE THREAD

**Issue by cashcon57** [nicolomantini/LinkedIn-Easy-Apply-Bot#125]
**the bug** here's the log:
"PS C:\Users\cashc\OneDrive\Documents\LinkedIn-Easy-Apply-Bot> python easyapplybot.py
Traceback (most recent call last):
  File "C:\Users\cashc\OneDrive\Documents\LinkedIn-Easy-Apply-Bot\easyapplybot.py", line 4, in <module>
    from future import annotations
ModuleNotFoundError: No module named 'future'"

**Screenshots**
If applicable, add screenshots of the LinkedIn page you are attempting to apply to. 

**Logs**
If applicable, attach your logs file found in `./logs/`

**Error Statement**
If applicable and not stated above, provide the error statement you are receiving. 

**Desktop (please complete the following information):**

**To Reproduce**
1. Install
2. Run.
3. Error

**Expected behavior**
The program is supposed to do something. It currently does nothing except spit out this error.

**Additional context**

**Comment by joaosilvalopes** [comment]
I made a similar bot in node.js https://github.com/joaosilvalopes/linkedin-easy-apply-bot, if you'd like to use it
