### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cody5138** [nicolomantini/LinkedIn-Easy-Apply-Bot#126]
**Describe the bug**
I installed ubuntu on windows then condra and all nesscary requirments. Every time i attempt to execute i get error for line 4 so i deleted line 4 and the bot will work but will it cannot find the phone number section so it shuts itself off

**Screenshots**
If applicable, add screenshots of the LinkedIn page you are attempting to apply to. 

**Logs**
If applicable, attach your logs file found in `./logs/`

**Error Statement**
(liab) cody5138@DESKTOP-ETNG53G:~/LinkedIn-Easy-Apply-Bot-master$ python3 easyapplybot.py
Traceback (most recent call last):
  File "/home/cody5138/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py", line 4, in <module>
    from future import annotations
ImportError: cannot import name 'annotations' from 'future' (/home/cody5138/.local/lib/python3.10/site-packages/future/__init__.py)

**Desktop (please complete the following information):**
 - Windows
 -Chrome
 - Version 110.0.5481.178 (Official Build) (64-bit)

**To Reproduce**
1. Go to ubuntu 
2. type in python3 easyapplybot.py
3. Click execute 

**Expected behavior**
Expected bot to run as the line that is casuing an error was updated 2 months ago

**Additional context**

**Comment by zwickidtek** [comment]
Comment out line 4 in easyapplybot.py
