### ISSUE TITLE
ImportError: cannot import name 'annotations' from 'future' 

### ISSUE THREAD

**Issue by toriporter1** [nicolomantini/LinkedIn-Easy-Apply-Bot#128]
chrisg@Chriss-MacBook-Pro-2 LinkedIn-Easy-Apply-Bot-master % python3 easyapplybot.py
Traceback (most recent call last):
  File "/Users/chrisg/Downloads/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py", line 4, in <module>
    from future import annotations
ImportError: cannot import name 'annotations' from 'future' (/Users/chrisg/anaconda3/lib/python3.10/site-packages/future/__init__.py)

**Comment by visionEye0** [comment]
having the same issue here too
