### ISSUE TITLE
ImportError: cannot import name 'annotations' 

### ISSUE THREAD

**Issue by klevinkona** [nicolomantini/LinkedIn-Easy-Apply-Bot#129]
Running via python 2.7 i get the following 

`python3 easyapplybot.py`

```
 File "easyapplybot.py", line 26
    def setupLogger() -> None:
                      ^
SyntaxError: invalid syntax
```
if i run via python3

`python3 easyapplybot.py`

`Traceback (most recent call last):
  File "/home/klevin/Desktop/tests/LinkedIn-Easy-Apply-Bot/easyapplybot.py", line 4, in <module>
    from future import annotations
ImportError: cannot import name 'annotations' from 'future' (/home/klevin/.local/lib/python3.9/site-packages/future/__init__.py)
`

**Comment by italojs** [comment]
just remove this line, it's not being used (i guess)
