### ISSUE TITLE
The Program stop at application page and throws an error.

### ISSUE THREAD

**Issue by ronnieotieno** [nicolomantini/LinkedIn-Easy-Apply-Bot#13]
The program throws an error in _normalizeXYArgs in _init_ file on pyautogui. Th error is 
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyautogui__init__.py", line 691, in _normalizeXYArgs

return Point(int(firstArg), int(secondArg)) # firstArg and secondArg are just x and y number values

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by OmarDTech** [comment]
im getting the same error

**Comment by ronnieotieno** [comment]
Hey Omar the program still doesnt work but I can help with the error, go to
def_lock function in easyapply file and change it to
` def avoid_lock(self):
        x, _ = pyautogui.position()
        pyautogui.moveTo(x + 200, pyautogui.position().y, duration=1.0)
        pyautogui.moveTo(x, pyautogui.position().y, duration=0.5)
        pyautogui.keyDown('ctrl')
        pyautogui.press('esc')
        pyautogui.keyUp('ctrl')
        time.sleep(0.5)
        pyautogui.press('esc')`

**Comment by ronnieotieno** [comment]
I
