### ISSUE TITLE
Filling missing info on application form

### ISSUE THREAD

**Issue by KingSamuelDavid** [nicolomantini/LinkedIn-Easy-Apply-Bot#136]
It seems there is no method to fill missing fields or to promp the user for input, looking ito implement something

**Comment by jjansen512** [comment]
The only way I've found around this issue is to manually enter the missing info and then the bot continues.

**Comment by jmarmstrong1207** [comment]
Having the same issue. The source code I believe does show that it should skip the application, but it doesn't.

**Comment by SolshineCode** [comment]
Perhaps we could implement a pause hotkey of some sort
