### ISSUE TITLE
Phone number is inputted into the name field sometimes

### ISSUE THREAD

**Issue by jmarmstrong1207** [nicolomantini/LinkedIn-Easy-Apply-Bot#139]
This issue happens infrequently. It's unfortunately hard to screenshot it due to the bot being quick. It should detect the correct phone number field. 

From what I see, the code looks for the first input field and wrongly assumes this input field will always be the phone number field. However, there are applications where the first input field is actually something like "First Name" and mistakenly puts it there

I don't think this piece of code is necessary as LinkedIn saves the phone number already, so reinputting it isn't needed.

**Comment by SolshineCode** [comment]
Could we just drop the phone number and add a clause for name to fix this, or do you think it's more complex?

**Comment by conradRz** [comment]
I deleted all the code relevant to inputting the phone number, as my browser simply remembers it, and pre-fills it. Therefore there is no need to ever enter it again. Simply search for "phone" and get deleting (assuming you know basic python).
