### ISSUE TITLE
ValueError when running script

### ISSUE THREAD

**Issue by sneakerush** [nicolomantini/LinkedIn-Easy-Apply-Bot#140]
File "/Users/admin/Documents/Python/LinkedIn-Easy-Apply-Bot/venv/lib/python3.10/site-packages/urllib3/util/timeout.py", line 156, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x102cbc820>, but it must be an int, float or None.

Any help? I filled out the config.yaml properly according to the README but issue persists.

**Comment by vaddisrinivas** [comment]
Facing the same issue, i am assuming that driver object is not being initialized and we might need to tweak the timeout

**Comment by matthewalampe** [comment]
I am getting the same error as well

**Comment by Kofi-D-Boateng** [comment]
There is most likely a timeout value that is not being used correctly. Could be a loose variable. Your best bet is to go into the code at the stacktrace and find the timeouts used in that area and fix it for yourself!

**Comment by Lucasnribeiro** [comment]
Update your selenium version pip install selenium==4.9.0

**Comment by vaddisrinivas** [comment]
I just checked, updating the selenium version works! thanks!

**Comment by davidksanusi** [comment]
Check my comment in the other git issue if still not fixed for you.

**Comment by Softlution2** [comment]
Hi guys. Does anyone has the urls for Chrome and Chrome Driver? I am struggling to find matching versions
