### ISSUE TITLE
OSX not running error ValueError: Timeout value connect was <object object at 0x100e74870>

### ISSUE THREAD

**Issue by babaz8** [nicolomantini/LinkedIn-Easy-Apply-Bot#142]
**Describe the bug**
Followed the instruction tried to run but I get this error
ValueError: Timeout value connect was <object object at 0x100e74870>, but it must be an int, float or None

**Screenshots**
If applicable, add screenshots of the LinkedIn page you are attempting to apply to. 

**Logs**
If applicable, attach your logs file found in `./logs/`

**Error Statement**
If applicable and not stated above, provide the error statement you are receiving. 

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 116.0.5845.96 

**To Reproduce**
1. Run python3.10 easyapplybot.py
2. No browser window is opening
3. Error **ValueError: Timeout value connect was <object object at 0x100e74870>, but it must be an int, float or None**

**Expected behavior**

**Additional context**

**Comment by stephenpark7** [comment]
Update Selenium, that should fix it (looks like someone raised a PR here) - https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/pull/141

**Comment by KaviHarjani** [comment]
Hey did you find a solution to this?

**Comment by davidksanusi** [comment]
Import the library and update your code to this:

from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service as ChromeService

driver = webdriver.Chrome(service=ChromeService(executable_path=ChromeDriverManager().install()))


Could you make sure you are using the most updated version of selenium as well? It took me a solid few hours to figure this out. 

On another note, the bot works but it can't fill out any applications.
<img width="825" alt="Screen Shot 2023-10-10 at 8 45 34 AM" src="https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/assets/77599701/29e281bb-d6cf-4bb6-8f3e-afcde4cef476">

**Comment by Jod929** [comment]
> from webdriver_manager.chrome import ChromeDriverManager from selenium.webdriver.chrome.service import Service as ChromeService
> 
> driver = webdriver.Chrome(service=ChromeService(executable_path=ChromeDriverManager().install()))

Awesome, nice progress! 

Im going to work on getting those application questions filled in.

**Comment by NB-123** [comment]
@Jod929 Did you end up fixing the issue? Thanks

**Comment by 210000o** [comment]
> @Jod929 Did you end up fixing the issue? Thanks

Try to uninstall selenium and install latest version of it. It works most of time

**Comment by NB-123** [comment]
@210000o I did that, but for some reason the Easy Apply button is never getting clicked. Even when I changed the code to force click it, it just gets stuck on the review page or some other page. Any other suggestions to get it to work with minimal changes? I changed the Selenium version and incorporated the above driver code as well. Thanks

**Comment by 210000o** [comment]
> @210000o I did that, but for some reason the Easy Apply button is never getting clicked. Even when I changed the code to force click it, it just gets stuck on the review page or some other page. Any other suggestions to get it to work with minimal changes? I changed the Selenium version and incorporated the above driver code as well. Thanks

Well I stuck here too. Iam trying to find out why

**Comment by NB-123** [comment]
@210000o et's keep each other updated. @Jod929 let us know if you managed to solve it. Thanks
