### ISSUE TITLE
It can't find the right location and EasyApply bottom 

### ISSUE THREAD

**Issue by 210000o** [nicolomantini/LinkedIn-Easy-Apply-Bot#147]
Is it just me or we all can't get the right job position?
This is config
![image](https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/assets/71466587/83c31c52-5429-4a8f-8ff0-9610f7df7755)
But this is what it searched
![image](https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/assets/71466587/2a23786e-2db2-48ec-9a7f-424a0273579a)

Also, it seems it can't locate EasyApply bottom correctly. Every time it tries to click, the mouse stays slightly outside the bottom, and somehow opens my system start menu and then closes it. After a few seconds of sleep, turn for another job.

Does anyone know what is happening?

**Comment by manboy40** [comment]
having the same issue, could be a recent update to LinkedIn? It's saying cannot find element. I'm getting this error: 
```
Stacktrace:
#0 0x56125320ed33 <unknown>
#1 0x561252ecbdbb <unknown>
#2 0x561252f1d3e1 <unknown>
#3 0x561252f0f583 <unknown>
#4 0x561252f45342 <unknown>
#5 0x561252f0edb9 <unknown>
#6 0x561252f4575e <unknown>
#7 0x561252f64297 <unknown>
#8 0x561252f450e3 <unknown>
#9 0x561252f0d044 <unknown>
#10 0x561252f0e44e <unknown>
#11 0x5612531d3861 <unknown>
#12 0x5612531d7785 <unknown>
#13 0x5612531c1285 <unknown>
#14 0x5612531d841f <unknown>
#15 0x5612531a520f <unknown>
#16 0x5612531fc028 <unknown>
#17 0x5612531fc1f7 <unknown>
#18 0x56125320ded4 <unknown>
#19 0x7f7157a94ac3 <unknown>

```

**Comment by BeanGrowthFab** [comment]
On line 298, it says EasyApplyButton = button[0]. I got it to work by changing it to EasyApplyButton = button[1]
