### ISSUE TITLE
Is it possible to filter jobs with keywords in job description?

### ISSUE THREAD

**Issue by wadid** [nicolomantini/LinkedIn-Easy-Apply-Bot#151]
Often it matters what is written in the job description e.g. certain programming languages. Often this relevant information is not in the job title. So it would be too unspecific to apply so broadly. Is there a way to apply a keyword filter on job description?
Or how does the application do that currently?

**Comment by ba2512005** [comment]
@wadid  You can use the blacklist portion of the config file and input any keywords that you don't want in there.
