### ISSUE TITLE
LinkedIn-Easy-Apply-Bot: Crash on Post-Login Page Navigation Due to NoSuchElementException

### ISSUE THREAD

**Issue by Kidus-berhanu** [nicolomantini/LinkedIn-Easy-Apply-Bot#153]
**Describe the bug**
The LinkedIn-Easy-Apply-Bot crashes after attempting to log in due to a NoSuchElementException error when searching for an element by its ID reset-password-submit-button

**Screenshots**
DevTools listening on ws://127.0.0.1:52589/devtools/browser/5b8e4fd6-9dda-4ae5-87b2-1abc3222d297
19:05:21 - INFO - Logging in.....Please wait :)  
Traceback (most recent call last):
  File "C:\Users\kidus\Downloads\LinkedIn-Easy-Apply-Bot-master\easyapplybot.py", line 633, in <module>
    bot = EasyApplyBot(parameters['username'],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidus\Downloads\LinkedIn-Easy-Apply-Bot-master\easyapplybot.py", line 85, in __init__
    self.start_linkedin(username, password)
  File "C:\Users\kidus\Downloads\LinkedIn-Easy-Apply-Bot-master\easyapplybot.py", line 167, in start_linkedin     
    oneclick_auth = self.browser.find_element(by='id', value='reset-password-submit-button')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidus\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 742, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidus\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\kidus\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="reset-password-submit-button"]"}
  (Session info: chrome=121.0.6167.140); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00F71673+52979]
        (No symbol) [0x00EF7961]
        (No symbol) [0x00DDDD3D]
        (No symbol) [0x00E15FBB]
        (No symbol) [0x00E160FB]
        (No symbol) [0x00E4CF92]
        (No symbol) [0x00E34534]
        (No symbol) [0x00E4B3FE]
        (No symbol) [0x00E34286]
        (No symbol) [0x00E0C063]
        (No symbol) [0x00E0CECD]
        GetHandleVerifier [0x01288D83+3294723]
        GetHandleVerifier [0x012C6CC2+3548482]
        GetHandleVerifier [0x012C1C9C+3527964]
        GetHandleVerifier [0x0100870E+671630]
        (No symbol) [0x00F01EB4]
        (No symbol) [0x00EFD808]
        (No symbol) [0x00EFD92D]
        (No symbol) [0x00EEF7E0]
        BaseThreadInitThunk [0x768E6739+25]
        RtlGetFullPathName_UEx [0x77928ACF+1215]
        RtlGetFullPathName_UEx [0x77928A9D+1165]

**Logs**
full LOG
./logs/04-Feb-24 18:20:34::__main__::INFO::{'phone_number': '<phone_number>', 'profile_path': '', 'positions': ['<position title 1>', '<position title 2>', '<position title 3>'], 'locations': ['<state>', 'Remote'], 'salary': '<yearly salary>', 'rate': '<hourly rate>', 'uploads': {'Resume': 'C:\\Users\\<user>\\Documents\\resume.docx', 'Cover Letter': 'C:\\Users\\<user>\\Documents\\cover letter.docx'}, 'output_filename': [None]}
./logs/04-Feb-24 18:20:34::__main__::INFO::Welcome to Easy Apply Bot
./logs/04-Feb-24 18:20:34::__main__::INFO::current directory is : C:\Users\kidus\Downloads\LinkedIn-Easy-Apply-Bot-master
./logs/04-Feb-24 18:20:34::__main__::INFO::[Errno 2] No such file or directory: 'output.csv'   jobIDs could not be loaded from CSV output.csv
./logs/04-Feb-24 18:20:45::__main__::INFO::Logging in.....Please wait :) 

**Error Statement**
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="reset-password-submit-button"]"}
(Session info: chrome=121.0.6167.140)

**Desktop (please complete the following information):**
Operating System: Windows 11
Python Version: 3.12
Selenium Version: 4.16.0
Browser and Version: Chrome 121.0.6167.140
pip list i am using all this 
attrs                   23.2.0
beautifulsoup4          4.12.2
certifi                 2023.11.17
cffi                    1.16.0
charset-normalizer      3.3.2
chromedrivermanager     0.0.1
cryptography            41.0.7
docopt                  0.6.2
fake-useragent          1.4.0
geographiclib           2.0
geopy                   2.4.1
h11                     0.14.0
idna                    3.6
MouseInfo               0.1.3
numpy                   1.26.3
outcome                 1.3.0.post0
packaging               23.2
pandas                  2.2.0
pip                     24.0
pipreqs                 0.4.13
pyarrow                 15.0.0
PyAutoGUI               0.9.54
pycparser               2.21
PyGetWindow             0.0.9
PyMsgBox                1.0.9
pyOpenSSL               23.3.0
pyperclip               1.8.2
pypiwin32               223
PyRect                  0.2.0
PyScreeze               0.1.30
PySocks                 1.7.1
python-dateutil         2.8.2
python-dotenv           1.0.0
pytweening              1.0.7
pytz                    2024.1
pywin32                 306
PyYAML                  6.0.1
requests                2.31.0
selenium                4.16.0
setuptools              69.0.3
six                     1.16.0
sniffio                 1.3.0
sortedcontainers        2.4.0
soupsieve               2.5
trio                    0.24.0
trio-websocket          0.11.1
tzdata                  2023.4
undetected-chromedriver 3.5.4
urllib3                 2.1.0
urllib3-secure-extra    0.1.0
validate_email          1.3
webdriver-manager       4.0.1
websockets              12.0
wget                    3.2
wheel                   0.42.0
wsproto                 1.2.0
yarg                    0.1.9

**To Reproduce**
Start the LinkedIn-Easy-Apply-Bot script with valid LinkedIn credentials passed as parameters.
Observe the script as it opens the Chrome browser, navigates to LinkedIn, and logs in.
Notice the script crashes immediately after the login process.

**Expected behavior**
The script should handle the post-login process smoothly, either navigating past the login verification/password reset prompt or continuing with the next steps if such a prompt is not present

**Additional context**
N/A

**Comment by ba2512005** [comment]
Should be fixed in new PR
