### ISSUE TITLE
jobs pagination do not swithc to second page

### ISSUE THREAD

**Issue by klevinkona** [nicolomantini/LinkedIn-Easy-Apply-Bot#157]
**Describe the bug**
The script does not go to the second page, keeps looping on the first page 

15:52:24 - INFO - Loading next job page?
15:52:33 - INFO - 20.0 minutes left in this search
15:52:33 - DEBUG - Sleeping for 2.8
15:52:41 - INFO - Loading next job page?
15:52:49 - INFO - 20.0 minutes left in this search
15:52:49 - DEBUG - Sleeping for 2.6
15:52:57 - INFO - Loading next job page?
15:53:06 - INFO - 20.0 minutes left in this search
15:53:06 - DEBUG - Sleeping for 2.8
15:53:13 - INFO - Loading next job page?
15:53:22 - INFO - 19.0 minutes left in this search
15:53:22 - DEBUG - Sleeping for 2.3
15:53:30 - INFO - Loading next job page?
15:53:38 - INFO - 19.0 minutes left in this search
15:53:38 - DEBUG - Sleeping for 1.7
15:53:53 - DEBUG - Easy Apply button not found
15:53:53 - INFO - Clicking the EASY apply button
15:53:58 - INFO - please answer the questions

**Screenshots**
If applicable, add screenshots of the LinkedIn page you are attempting to apply to. 

**Logs**
`./logs/08-Feb-24 15:57:48::__main__::INFO::Loading next job page?
./logs/08-Feb-24 15:57:57::__main__::INFO::15.0 minutes left in this search
./logs/08-Feb-24 15:57:57::__main__::DEBUG::Sleeping for 1.9
./logs/08-Feb-24 15:58:04::__main__::INFO::Loading next job page?
./logs/08-Feb-24 15:58:12::__main__::INFO::14.0 minutes left in this search
./logs/08-Feb-24 15:58:12::__main__::DEBUG::Sleeping for 2.0
./logs/08-Feb-24 15:58:20::__main__::INFO::Loading next job page?
./logs/08-Feb-24 15:58:29::__main__::INFO::14.0 minutes left in this search
./logs/08-Feb-24 15:58:29::__main__::DEBUG::Sleeping for 1.9
./logs/08-Feb-24 15:58:37::__main__::INFO::Loading next job page?
./logs/08-Feb-24 15:58:45::__main__::INFO::14.0 minutes left in this search
./logs/08-Feb-24 15:58:45::__main__::DEBUG::Sleeping for 1.7
./logs/08-Feb-24 15:58:52::__main__::INFO::Loading next job page?
./logs/08-Feb-24 15:59:01::__main__::INFO::14.0 minutes left in this search
./logs/08-Feb-24 15:59:01::__main__::DEBUG::Sleeping for 2.8
./logs/08-Feb-24 15:59:09::__main__::INFO::Loading next job page?
./logs/08-Feb-24 15:59:17::__main__::INFO::13.0 minutes left in this search
./logs/08-Feb-24 15:59:17::__main__::DEBUG::Sleeping for 2.3
./logs/08-Feb-24 15:59:25::__main__::INFO::Loading next job page?
./logs/08-Feb-24 15:59:33::__main__::INFO::13.0 minutes left in this search
./logs/08-Feb-24 15:59:33::__main__::DEBUG::Sleeping for 1.9
./logs/08-Feb-24 15:59:41::__main__::INFO::Loading next job page?
./logs/08-Feb-24 15:59:49::__main__::INFO::13.0 minutes left in this search
./logs/08-Feb-24 15:59:49::__main__::DEBUG::Sleeping for 2.5
./logs/08-Feb-24 15:59:57::__main__::INFO::Loading next job page?
./logs/08-Feb-24 16:00:05::__main__::INFO::13.0 minutes left in this search
./logs/08-Feb-24 16:00:05::__main__::DEBUG::Sleeping for 2.6`

**Error Statement**
If applicable and not stated above, provide the error statement you are receiving. 

**Desktop (please complete the following information):**
 - xubuntu 22.04
 - Chrome
 - Version Version 120.0.6099.216 (Official Build) (64-bit)

**To Reproduce**
 1. Install xubuntu 22.04
 2. clone the repository
 3. install chrome ( sudo dpkg -i google-chrome-stable_current_amd64.deb) 
 4. Install needed packqges
      (  
          sudo apt install python3-pip  
          pip3 install -r requirements.txt 
          pip install webdriver_manager    
      )
 5. Let it run for some minutes, 
 6. Pagination do not work
 7

**Expected behavior**
should switch to second page

**Comment by Saltiola7** [comment]
Same problem on mac & chrome.

**Comment by farrenhi** [comment]
I have seen same issue here on windows 10 and chrome.

one solution i did (not sure if correct)

                    self.browser, jobs_per_page = self.next_jobs_page(position,
                                                                      location,
                                                                      jobs_per_page + 25)
                                                                      
                                                                      so I did "+ 25" as above.

**Comment by amitai1997** [comment]
same problem on ubuntu WSL on windows

**Comment by klevinkona** [comment]
> I have seen same issue here on windows 10 and chrome.
> 
> one solution i did (not sure if correct)
> 
> ```
>                 self.browser, jobs_per_page = self.next_jobs_page(position,
>                                                                   location,
>                                                                   jobs_per_page + 25)
>                                                                   
>                                                                   so I did "+ 25" as above.
> ```

Looks like this works, @farrenhi can you push it to the repo?
