### ISSUE TITLE
Remote locations dont work or there is no documentation how it should work

### ISSUE THREAD

**Issue by Saltiola7** [nicolomantini/LinkedIn-Easy-Apply-Bot#158]
on MacOs 14.3 & chrome
the script does not use remote correctly

in the config if I put

- Texas
- Remote

it sometimes is remote sometimes not.

There could be a simple way to just switch remote on always and define the locations separately.

**Comment by ba2512005** [comment]
It randomizes the combinations so sometimes it will choose remote, other times it will choose texas. 
If you want only to search for remote jobs, comment out texas
