### ISSUE TITLE
Agree terms & Conditions

### ISSUE THREAD

**Issue by klevinkona** [nicolomantini/LinkedIn-Easy-Apply-Bot#160]
**Describe the bug**
Include check box agreement in automation process

**Screenshots**
![2024-03-03_18-54](https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/assets/1549891/17181d94-094c-437c-b216-73a8aeaf5229)

**Logs**
18:53:50 - INFO - Please answer the questions, waiting 5 seconds...
18:53:55 - INFO - Skipping application
18:53:56 - INFO - Please answer the questions, waiting 5 seconds...
18:54:01 - INFO - Skipping application
18:54:02 - INFO - Please answer the questions, waiting 5 seconds...
18:54:07 - INFO - Skipping application
18:54:08 - INFO - Please answer the questions, waiting 5 seconds...
18:54:13 - INFO - Skipping application
18:54:15 - INFO - Please answer the questions,

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 
 - Browser Chrome
 - Version 121.0.6167.184 (Official Build) (64-bit)

**To Reproduce**
1.let the script running
2. it will stop on the form shared in the above screenshot

**Expected behavior**

**Additional context**

**Comment by daddywolf** [comment]
same problem
