### ISSUE TITLE
Bot submits CV every time it opens a Job

### ISSUE THREAD

**Issue by hilda04** [nicolomantini/LinkedIn-Easy-Apply-Bot#176]
Everytime the BOT applies to a job once it starts running, it submits the CV, Is there a way to change the code so that on initialisation the bot submits the CV on the first application, and then for the rest it just picks that CV that it used before (which would already be stored in LinkedIn by then)

**Comment by azjz92** [comment]
https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI join this group it is a better bot and still being maintained :)
