### ISSUE TITLE
GUI switch

### ISSUE THREAD

**Issue by MikeDrones** [nicolomantini/LinkedIn-Easy-Apply-Bot#2]
GUI switch is at line 315 in easyapplybot.py if you could put that in the readme that would be cool.
line 117 and 118 were causing errors, without knowing what they are for i ended up just commenting them out and everything still worked. if you could add comment for their function that would make it easier to fix.
Thanks

**Comment by nicolomantini** [comment]
Hi thanks for your comments !

please submit a pull request with the modifications you have done, so everyone can benefit :)

**Comment by MikeDrones** [comment]
Ok sounds good.

**Comment by nicolomantini** [comment]
Thanks for your contribution, I will close this issue :))
