### ISSUE TITLE
It doesnt work, it log on Linkedin but i cant apply

### ISSUE THREAD

**Issue by sarment0** [nicolomantini/LinkedIn-Easy-Apply-Bot#21]
I have a few issues running the script. 

1) I can't properly login, I fill the form with the correct e-mail and password, but somehow the script fill the form with less characters in password field (I had to harcode the password in the script to work). 
2) It doesnt work with Portuguese, it opens the position page and it doesnt click apply "Enviar Candidatura", it does the same in all positions.

**Comment by krapes** [comment]
Ya, what happened was I wasn't using the GUI but instead was passing a list of positions/locations in a python script.

The following should help with issue number 1:

I've created a new [pull request](https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/pull/25) contain a `config.yaml` file that should fix this issue. 

or you can download it from [my fork](https://github.com/krapes/LinkedIn-Easy-Apply-Bot.git)
