### ISSUE TITLE
When searching for position, it only accepts the first letter

### ISSUE THREAD

**Issue by Spectrem12** [nicolomantini/LinkedIn-Easy-Apply-Bot#22]
Job search for Embedded Software Engineer, but it only searched for 'E'

`    def start_apply(self):
          #self.wait_for_login()
          self.fill_data()
          #for position in self.positions:
           #   for location in self.locations:
           print(f"Applying to {position}: {location}")
           #location = "&location=" + location
           self.applications_loop(position, location)
           self.finish_apply()
`

For a temp fix, I commented out the commented out lines above.

**Comment by nikolaknez** [comment]
Same issue.

**Comment by nikolaknez** [comment]
Also besides taking just the first letter for the position, it just defaults to : " United States" it doesn't take into consideration the Country input from GUI.

**Comment by krapes** [comment]
Ya, what happen is I didn't use the GUI but instead was passing a list of positions/locations in a python script.

I've created a new [pull request](https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/pull/25) contain a `config.yaml` file that should fix this issue. 

or you can download it from [my fork](https://github.com/krapes/LinkedIn-Easy-Apply-Bot.git)

**Comment by nikolaknez** [comment]
Thanks 

Also

Line 350:

self.browser.get(
            "https://www.linkedin.com/jobs/search/?f_LF=f_AL&keywords=" +
            position + location + "&start=" + str(jobs_per_page)

Shall be as :

self.browser.get(
            "https://www.linkedin.com/jobs/search/?f_LF=f_AL&keywords=" +
            position + "&location=" + location + "&start=" + str(jobs_per_page)


Need to add the &location ... otherwise it merged into job position !

Best Regards,
Mr Nikola Knezevic, Ph.M, PgMP, PMP, CSM, MSP & PRINCE2 Practitioner, MAPM,MIPMA

**Comment by krapes** [comment]
Hey @nikolaknez 

the "&location=" string is actually added in the `start_apply` function.

```
def start_apply(self, positions, locations):
		start = time.time()
		self.fill_data()

		combos = []
		while len(combos) < len(positions) * len(locations):
			position = positions[random.randint(0, len(positions) - 1)]
			location = locations[random.randint(0, len(locations) - 1)]
			combo = (position, location)
			if combo not in combos:
				combos.append(combo)
				print(f"Applying to {position}: {location}")
				location = "&location=" + location
				self.applications_loop(position, location)
			if len(combos) > 20:
				break
		self.finish_apply()
```

I'm not sure why it was originally written that why, the answer might need a little more detective work.

**Comment by nikolaknez** [comment]
Thanks. Excellent.

**Comment by nikolaknez** [comment]
@krapes Do you know what is an operator name to exclude company? I know the  include operator is f_C=. If I want to exclude there is an operator in sales version. Normal <> will not work with f_C. I guess there is another "f_???" for excluding.

**Comment by krapes** [comment]
I don't know, I just use a blacklist. 

I added the blacklist option to the config.yaml file in [this pull request](https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/pull/27) if you want to use it to filter companies.
