### ISSUE TITLE
Unable to answer "additional questions" during application

### ISSUE THREAD

**Issue by Spectrem12** [nicolomantini/LinkedIn-Easy-Apply-Bot#28]
Some job applications have "additional questions" at the end of the application that are required before submitting the application. These questions are seemingly standardized and should be able to be answered generically.
Examples of questions:

- How many years of experience do you have in X
- Do you require sponsorship to work in the United States
- Are you legally authorized to work in the United States

Please assign this issue to me, as I am already working on this. (if you wouldnt mind :) )@nicolomantini

**Comment by nicolomantini** [comment]
@krapes

**Comment by ZaneBaylon** [comment]
> Some job applications have "additional questions" at the end of the application that are required before submitting the application. These questions are seemingly standardized and should be able to be answered generically. Examples of questions:
> 
> * How many years of experience do you have in X
> * Do you require sponsorship to work in the United States
> * Are you legally authorized to work in the United States
> 
> Please assign this issue to me, as I am already working on this. (if you wouldnt mind :) )@nicolomantini

A little bit of a lag, but I successfully was able to implement this using an input library and a selenium engine. Answers around 40 of the most common questions and applies each question prompt to all possible HTML input formats. Lmk if you'd like to chat about it!
