### ISSUE TITLE
cannot apply to this job error with "selenium.common.exceptions.TimeoutException" message

### ISSUE THREAD

**Issue by charlieblaze24k** [nicolomantini/LinkedIn-Easy-Apply-Bot#33]
Hello,

I'm trying to use your bot to apply for jobs in LinkedIn. I have successfully installed your software and ran on my Windows laptop, however it is erroring out after applying to 1 job. see the screen shots below

![linkedin_jobs_bot_error_2](https://user-images.githubusercontent.com/68096425/87860740-86189980-c905-11ea-89c2-5b8795bb7577.png)

![linkedin_jobs_bot_error_1](https://user-images.githubusercontent.com/68096425/87860699-2a4e1080-c905-11ea-987c-f3d3854e124d.png)

Can you please advise me how to proceed? Thanks.

**Comment by krapes** [comment]
It's hard to say without more context, but `Timeout` errors are usually because the browser couldn't interact with the webpage in the allotted time. A common culprit is an intermittent internet connection.

**Comment by alijnmerchant21** [comment]
<img width="1792" alt="Screen Shot 2020-07-23 at 12 23 36 AM" src="https://user-images.githubusercontent.com/44069404/88216612-f2cfc300-cc7a-11ea-8930-956ac98242d2.png">


I'm seeing a similar error. It applies for a few jobs and then times out.

**Comment by krapes** [comment]
@alijnmerchant21 I delete your picture because it was displaying you username/password.

**Comment by krapes** [comment]
@alijnmerchant21

There appears to be an issue in your configuration. The dictionary should be:

```
'uploads': {'Resume': 'PATH', 'Cover Letter': 'PATH'}
```

Make sure your configuration file has those lines indented. 

```
 uploads:
    Resume: # PATH TO Resume 
    Cover Letter: # PATH TO cover letter
    Photo: # PATH TO photo
```

**Comment by alijnmerchant21** [comment]
> @alijnmerchant21 I delete your picture because it was displaying you username/password.

Oh Damn! Thanks

**Comment by charlieblaze24k** [comment]
Hello @krapes, thanks for looking at the issue. while bad internet connection might be possible, that might be unlikely because i was running this in a public library with good internet connection. i saw the script was able to apply to one or two jobs before hitting this timeout issue. I would like to diagnose this issue further and find a solution. is it possible for me to run this script in debug mode so i might be able to provide you with additional logs to rootcause the issue in detail? let me know.

**Comment by krapes** [comment]
Hey @charlieblaze24k,

:/ that sucks to hear. If you clone the newest version of the master branch it now writes logs to a folder called `./logs/`

Let's use that to try to debug :)
