### ISSUE TITLE
ModuleNotFoundError: No module named 'login_v06'

### ISSUE THREAD

**Issue by alijnmerchant21** [nicolomantini/LinkedIn-Easy-Apply-Bot#35]
ModuleNotFoundError: No module named 'login_v06'

**Comment by krapes** [comment]
Hard to say without more context.

**Comment by alijnmerchant21** [comment]
<img width="1792" alt="Screen Shot 2020-07-23 at 12 17 06 AM" src="https://user-images.githubusercontent.com/44069404/88215888-f282f800-cc79-11ea-8ff6-0bc9b41b63c6.png">

**Comment by alijnmerchant21** [comment]
<img width="1792" alt="Screen Shot 2020-07-23 at 12 19 22 AM" src="https://user-images.githubusercontent.com/44069404/88216078-3c6bde00-cc7a-11ea-92c5-ab7569ab2cb5.png">

**Comment by krapes** [comment]
`easyapplybot_Premum.py` hasn't been updated. I would suggest using `easyapplybot`

**Comment by alijnmerchant21** [comment]
Okay!
