### ISSUE TITLE
UnboundLocalError: local variable 'result' referenced before assignment

### ISSUE THREAD

**Issue by alijnmerchant21** [nicolomantini/LinkedIn-Easy-Apply-Bot#36]
<img width="1792" alt="Screen Shot 2020-07-23 at 1 18 24 AM" src="https://user-images.githubusercontent.com/44069404/88221835-a7211780-cc82-11ea-8f73-67b491a23def.png">

**Comment by krapes** [comment]
I need more context on this issue. What was you're config.yaml, OS, and job description it was attempting to apply to
