### ISSUE TITLE
Heroku Support to automate the bot.

### ISSUE THREAD

**Issue by alijnmerchant21** [nicolomantini/LinkedIn-Easy-Apply-Bot#40]
Hey Guys! I'm trying to move this python script to Heroku to automate the bot even further. I'm facing some issues with that. 

If the team thinks its a good enhancement feature, I can share my script code and the issues I'm facing. 

Thanks!

**Comment by krapes** [comment]
I like the idea :)
I don't know if @nicolomantini  or @Spectrem12 have any objections?

**Comment by Spectrem12** [comment]
My experience doesnt really fall into web based apps, so what is the benefit of using Heroku? Is Heroku and Github mutually exclusive? What would the plan be once moved to Heroku?

**Comment by alijnmerchant21** [comment]
@Spectrem12 The idea is - the user can locally push their configured script to a Heroku server. The script will then keep running in background with little to no interference from user.
This will truly **automate** job application process.

@krapes Thanks!

**Comment by Spectrem12** [comment]
Sounds good to me. Im interested.
