### ISSUE TITLE
Timeout Exception

### ISSUE THREAD

**Issue by alijnmerchant21** [nicolomantini/LinkedIn-Easy-Apply-Bot#41]
Team!

**I'm seeing the following error:** *(Screenshot Attached)*

<img width="1792" alt="Screen Shot 2020-07-31 at 11 29 46 PM" src="https://user-images.githubusercontent.com/44069404/89063830-834a8980-d386-11ea-84d4-1fd1ca322e98.png">

Also, I have noticed while applying jobs - the bot searches and skips the job postings without *Easy Apply*. Once it reaches a job with *Easy Apply* it applies for that job and throws this error. 

Please Advice.

**Comment by krapes** [comment]
Hmmm... The newest push to master now outputs logs into a `.logs/` folder. If you rerun it with that update we can use the log file to debug. 

Also,

1. What OS are you using?
2. Can you send a screenshot of the linkedin page it's trying to apply to

**Comment by alijnmerchant21** [comment]
@krapes 

1. I'm using Mac OS.
2. LinkedIn page it applied last.

<img width="847" alt="Screen Shot 2020-08-01 at 9 31 44 AM" src="https://user-images.githubusercontent.com/44069404/89093682-19f46600-d3da-11ea-8c94-d9c226e51129.png">

Once it applies to a job with *Easy Apply* it waits for a few seconds before throwing this timeout exception.

**Screenshot of error**

<img width="1557" alt="Screen Shot 2020-08-01 at 9 32 33 AM" src="https://user-images.githubusercontent.com/44069404/89093705-558f3000-d3da-11ea-8b17-cbc4312a7988.png">

**Log file Screenshot**

<img width="1460" alt="Screen Shot 2020-08-01 at 9 38 18 AM" src="https://user-images.githubusercontent.com/44069404/89093759-d0584b00-d3da-11ea-827c-e0745b02c856.png">

**Comment by Spectrem12** [comment]
It cant find the close window button to close the final window. 

@krapes  - Im not really sure we need to actually close out that window, but rather just return submitted T/F to the calling function. Is there is an error in the code, while applying then I think at the very end it still checks for the close button.. 

Id also say the Submitted vs non submitted is not really straight forward. If its submitted or not, it always is output to the csv file.

**Comment by krapes** [comment]
Agreed, I'm curious as to why it can't find the close button, but all the same I'm going to remove that step

**Comment by alijnmerchant21** [comment]
@krapes One thing I noticed.. after submitting application, the window automatically closes after a second. So it would be a good decision to eliminate that step to ensure timeout error doesn't occur.. as it keeps waiting for the 'submit' button.

**Comment by krapes** [comment]
Hey @alijnmerchant21,

I eliminated the close button last weekend. Try cloning the new master branch and see if that fixes your problem
