### ISSUE TITLE
We have integrated your code in socialbotspy organisation

### ISSUE THREAD

**Issue by ishandutta2007** [nicolomantini/LinkedIn-Easy-Apply-Bot#5]
Hi @nicolomantini,

We have integrated your code as an [API](https://github.com/socialbotspy/LinkedinPy#jobs-easy-apply) of https://github.com/socialbotspy/LinkedinPy . Incase you are interested in being a contributor of it such that your code get better maintained at one place by a bigger community, let us know we can add you to the organisation.

Cheers,
Ishan

PS: Apologies for reaching out to you via issues as I couldn't find any other means.

**Comment by barsof** [comment]
![image](https://user-images.githubusercontent.com/47591116/73739990-fb295580-474f-11ea-85c6-0cfc45278024.png)

**Comment by ishandutta2007** [comment]
Yes it's been taken down for security reasons.
