### ISSUE TITLE
Doesn't work beyond a page!

### ISSUE THREAD

**Issue by anofranc1** [nicolomantini/LinkedIn-Easy-Apply-Bot#52]
Tried like many times and couple of computers.
It either go to sleep and then exits OR applies to max of 1 page. Doesn't work basically.
Not sure if i am doing something wrong

**Comment by moover9999** [comment]
Yes, I am facing the same issue. Does not work after the 1st page

**Comment by PAndreew** [comment]
Please see my pull request, this is resolved for Chrome.

**Comment by krapes** [comment]
Hey @PAndreew, I'd love to merge in your pull request, there are just a few pending requests that we need to take care of

**Comment by krapes** [comment]
@moover9999 The pull request mentioned above has been merged
