### ISSUE TITLE
Remote location is set to Remote, OR, US

### ISSUE THREAD

**Issue by naokishami** [nicolomantini/LinkedIn-Easy-Apply-Bot#57]
**Describe the bug**
In my config file, I have one of my locations set to 'Remote'. However when I run the script, the location changes to 'Remote, OR, US' in the LinkedIn search. 

**Screenshots**
![Screen Shot 2020-11-15 at 12 23 49 AM](https://user-images.githubusercontent.com/19796206/99150565-d992cc80-26d8-11eb-9ec4-698e9e547dd3.png)

**Expected behavior**
Would expect the remote location to remain as remote. Instead, it is somehow set to remote, OR, US

**Comment by krapes** [comment]
@naokishami 
Could you share your config settings and/or other details to reproduce the error?

![image](https://user-images.githubusercontent.com/6612207/100516774-e09fed00-3164-11eb-874b-c819ce5ba601.png)

When I run it with the below config.yaml I see the above result:
```
positions:
- Data Scientist
- # Another position you want to search for
- # A third position you want to search for

locations:
- Remote
```

**Comment by PeytonJohnson** [comment]
I'm also having a problem with this any help?
