### ISSUE TITLE
  File "easyapplybot.py", line 444, in <module>     for key in uploads.keys(): AttributeError: 'NoneType' object has no attribute 'keys

### ISSUE THREAD

**Issue by belgareth** [nicolomantini/LinkedIn-Easy-Apply-Bot#58]
File "easyapplybot.py", line 444, in <module>
    for key in uploads.keys():
AttributeError: 'NoneType' object has no attribute 'keys

error in windows

line 444
```
	for key in uploads.keys():
		assert uploads[key] != None
```

**Comment by krapes** [comment]
@belgareth  A modification has been made to address this case. Let me know if it does or doesn't work :)
