### ISSUE TITLE
Cannot apply any job

### ISSUE THREAD

**Issue by us** [nicolomantini/LinkedIn-Easy-Apply-Bot#6]
It doesn't find submit button.
```Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), 'Submit application')]"}```

**Comment by Slab2020** [comment]
Same for me. It seems that it doesn't find the Submit button. Do you have any insight on how to fix that ?

**Comment by Tashaa78** [comment]
Created a pull request for this fix.

**Comment by rajathn8** [comment]
Comment the print statement out:s it is not necessary.

**Comment by rajathn8** [comment]
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="file-browse-input"]"}
  (Session info: chrome=80.0.3987.122)

cannot apply to this job
