### ISSUE TITLE
The script failed to be installed on pip3

### ISSUE THREAD

**Issue by abozaid-ibrahim** [nicolomantini/LinkedIn-Easy-Apply-Bot#61]
**Describe the bug**
I just installed python to my mac, it has only the pip3 command when I hit pip3 install requiremnt.txt
I got a ton of errors 
You could find the logs below
**Screenshots**
![image](https://user-images.githubusercontent.com/5619930/102887296-f6988900-4456-11eb-94b4-e1bca5f7cefe.png)

**Logs**
 ERROR: Command errored out with exit status 1:
   command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/7k/dhn34tsn6ws3fsts9dt78_mr0000gp/T/pip-build-env-gys917s1/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.29.13' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version>='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"''
       cwd: None
  Complete output (4388 lines):
  Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.7" and platform_system == "AIX"' don't match your environment
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/ce/3c/096ac70aeb74485a2e7ab6f8146ea41cb4cecd955fdb2f30d51b51d7d146/setuptools-51.1.0-py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
  Collecting Cython>=0.29.13
    Using cached https://files.pythonhosted.org/packages/ad/4b/9e53bcce3c959fd0db143626e573210bba07be810fe8d7296373948c4183/Cython-0.29.21-py2.py3-none-any.whl
  Collecting numpy==1.14.5
    Downloading https://files.pythonhosted.org/packages/d5/6e/f00492653d0fdf6497a181a1c1d46bbea5a2383e7faf4c8ca6d6f3d2581d/numpy-1.14.5.zip (4.9MB)
  Building wheels for collected packages: numpy
    Building wheel for numpy (setup.py): started
    Building wheel for numpy (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7k/dhn34tsn6ws3fsts9dt78_mr0000gp/T/pip-install-tn6vz1qr/numpy/setup.py'"'"'; __file__='"'"'/private/var/folders/7k/dhn34tsn6ws3fsts9dt78_mr0000gp/T/pip-install-tn6vz1qr/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/7k/dhn34tsn6ws3fsts9dt78_mr0000gp/T/pip-wheel-0zawlzmh --python-tag cp38
         cwd: /private/var/folders/7k/dhn34tsn6ws3fsts9dt78_mr0000gp/T/pip-install-tn6vz1qr/numpy/
    Complete output (4069 lines):
    Running from numpy source directory.
    /private/var/folders/7k/dhn34tsn6ws3fsts9dt78_mr0000gp/T/pip-install-tn6vz1qr/numpy/numpy/distutils/misc_util.py:464: SyntaxWarning: "is" with a literal. Did you mean "=="?
      return is_string(s) and ('*' in s or '?' is s)
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE
  
    blis_info:

**Comment by krapes** [comment]
Hey @abuzeid-ibrahim 

Try following one of these:
https://stackoverflow.com/questions/41241468/error-pip-install-scipy
https://forums.developer.nvidia.com/t/pip-install-something-but-error-with-could-not-find-a-satisfies-version/66300/3

**Comment by abuzeid-ibrahim** [comment]
as far as I understand the issue is from configparser version, I tried to upgrade the version to 5.0.1 but Also it doesn't work.
```
ERROR: Could not find a version that satisfies the requirement configparser==5.0.0 (from -r requirements.txt (line 6)) (from versions: 3.2.0.post1, 3.2.0.post2, 3.2.0.post3, 3.3.0.post1, 3.3.0.post2, 3.5.0b1, 3.5.0b2, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5, 3.8.1, 4.0.2)
ERROR: No matching distribution found for configparser==5.0.1 (from -r requirements.txt (line 6))
```

**Comment by abuzeid-ibrahim** [comment]
The same issue happens with MouseInfo 
![image](https://user-images.githubusercontent.com/5619930/102911604-8f8dcb00-447c-11eb-93ae-0f27765136ea.png)

**Comment by abuzeid-ibrahim** [comment]
I also tried it with both python2 and python 3 but it always has an issue with the dependencies versions

**Comment by krapes** [comment]
@abuzeid-ibrahim 
The latest version of master has only the minimum package requirements and does not include version requirements. See if that helps with the conflicts
