### ISSUE TITLE
Someone is stealing your code and claiming as it's own.

### ISSUE THREAD

**Issue by abn5x** [nicolomantini/LinkedIn-Easy-Apply-Bot#63]
This guy literally copied your work and claims it as it's own.

https://github.com/davidpeinao/ShurBot_LinkedIn

**Comment by e-vdev** [comment]
i can confirm it.
He is using a copy of the code and promoting it in forums, with his name.

**Comment by nicolomantini** [comment]
Thanks for the notification.
It is a pity this guy didn't want to contribute to this code...

**Comment by abn5x** [comment]
> Thanks for the notification.
> It is a pity this guy didn't want to contribute to this code...

yeah.. he even tried to justify himself in the private forum he posted "his work"
