### ISSUE TITLE
Linkedin Disconnects the Bot

### ISSUE THREAD

**Issue by ydeliorman** [nicolomantini/LinkedIn-Easy-Apply-Bot#69]
I have pulled your repository and only changed the config.yaml file. After few minutes(around an hour), my account signed out. Is it only related with me?

**Comment by krapes** [comment]
@ydeliorman No, you probably got flagged by Linkedin as being a bot :(

**Comment by ydeliorman** [comment]
Somehow I didn't face with the problem. Thank you for your answer :)
