### ISSUE TITLE
Bots Follows the Company and Doesn't Accept Privacy Settings

### ISSUE THREAD

**Issue by ydeliorman** [nicolomantini/LinkedIn-Easy-Apply-Bot#70]
- After submitting the application, bot does not unselect "follow ... company".
- Bot does not select "I agree privacy statement..." checkbox.

I have fixed those issues. If you want, I can make a pull request.

**Comment by krapes** [comment]
@ydeliorman Ya! :)

**Comment by KushalBKusram** [comment]
Hey guys! Any update on not selecting "follow company"? Or an idea of how I could implement that in this code. Thanks!

**Comment by ydeliorman** [comment]
Hello, I was on a vacation. I will make a pull request when I go back to home. Sorry for delay :(

**Comment by ydeliorman** [comment]
@KushalBKusram, @krapes hello again guys. Pull request is [here](https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/pull/71).

**Comment by KushalBKusram** [comment]
Thank you @ydeliorman!

**Comment by ydeliorman** [comment]
You are welcome 👍 @KushalBKusram
