### ISSUE TITLE
line : 269 - 270  IndexError:list index out of range (browserTitle.split(' | ')[1])

### ISSUE THREAD

**Issue by Oscarwang666** [nicolomantini/LinkedIn-Easy-Apply-Bot#77]
**Describe the bug**

line : 269 - 270  

IndexError:list index out of range

**Screenshots**
![3951617853752_ pic](https://user-images.githubusercontent.com/34757116/113965694-b7622e00-97e2-11eb-9a1e-d2885cf88251.jpg)

perhaps add try catch ?
```
try:
     job = re_extract(browserTitle.split(' | ')[0], r"\(?\d?\)?\s?(\w.*)")
     company = re_extract(browserTitle.split(' | ')[1], r"(\w.*)")
except:
```

**Comment by Neiljoshi97** [comment]
I'm getting a similar issue. 
![Capture](https://user-images.githubusercontent.com/75547264/115095907-026df680-9ef1-11eb-832b-28f3318ab100.JPG)
