### ISSUE TITLE
necessary enhancement !!

### ISSUE THREAD

**Issue by Sy3Omda** [nicolomantini/LinkedIn-Easy-Apply-Bot#82]
First of all thank you for this amazon bot :)
i just need to clarify some enhancement need to be implemented such as
Questions asked during submitting easy apply like 

- How many years of experience do you have with [role such as Cybersecurity]?
- Are you legally authorized to work in [country name]?
- Will you now or in the future require sponsorship for employment visa status ?

those questions is flexible and 50% of applications i saw those questions are included
so is there anyway to include theme in `config.yaml` or even give the user the ability to include any questions by adding them to 
config file and wildcard the rest of question as following .
`Are you legally authorized to work in [*]?` 

Thank you

**Comment by NathanDuma** [comment]
Go to my profile, I have this in my bot.

**Comment by EdwardOak** [comment]
I thought of plugin my Google Vision systems on this to simply repeat the requirements in the job's offer description. 

It's always: 
Requirements: 4 years of Drupal

and then:
How many years of Drupal experience do you have
