### ISSUE TITLE
Loops "Lock avoided / Sleeping"

### ISSUE THREAD

**Issue by EdwardOak** [nicolomantini/LinkedIn-Easy-Apply-Bot#86]
Bot stopped working properly after a few days. 

Now it just loops on "Lock Avoided / Sleeping X.X"

Any idea?

**Comment by EdwardOak** [comment]
If I manage to get it to work by manually clicking a page or something, it'll try 1 easy apply and "switch job" then will loop again

**Comment by EdwardOak** [comment]
"Position 76:
 Content Writer - Digital Marketer | Nasdasdsdasddas | LinkedIn 
 * has Easy Apply Button 

16:07:04 - INFO - ****************************************


                        Going to next jobs page, YEAAAHHH!!
                        ****************************************


^[^[^[^[16:07:19 - INFO - Lock avoided.
16:07:39 - INFO - 592.0 minutes left in this search
16:07:39 - DEBUG - Sleeping for 4.2
16:08:29 - INFO - The button does not exist.
16:08:29 - INFO - 
Position 101:
 Content Writer - Digital Marketer | asddasadsasddasdaasddasads. | LinkedIn 
 * Doesn't have Easy Apply Button 

16:08:29 - INFO - ****************************************


                        Going to next jobs page, YEAAAHHH!!
                        ****************************************


^[^[^[^[16:08:44 - INFO - Lock avoided.
16:09:04 - INFO - 591.0 minutes left in this search
16:09:04 - DEBUG - Sleeping for 3.9
16:09:46 - INFO - The button does not exist.
16:09:46 - INFO - 
Position 126:
 Full-Stack Developer (C# .NET, Angular) | Wdasdasasdasdasdasd | LinkedIn 
 * Doesn't have Easy Apply Button 

16:09:46 - INFO - ****************************************
"

**Comment by klevinkona** [comment]
The same issue, i see the job have easy apply, but yet no apply process
