### ISSUE TITLE
Getting this issue

### ISSUE THREAD

**Issue by kapil303196** [nicolomantini/LinkedIn-Easy-Apply-Bot#88]
![image](https://user-images.githubusercontent.com/20143393/138110113-c45264a4-d03f-48fe-9799-f34d7b30454d.png)

**Comment by PhilipPhil** [comment]
I have the same issue

**Comment by GNLaForgia-Bruner** [comment]
Also getting this error. @krapes @nicolomantini 

Can we get a fix on this ASAP?

**Comment by GNLaForgia-Bruner** [comment]
This issue has been open for 20+ days. Is anyone on this project still providing service?

**Comment by lokyGit** [comment]
Getting the same issue, can we fix this?

**Comment by NathanDuma** [comment]
The fix would just be to use my bot instead: https://github.com/NathanDuma/LinkedIn-Easy-Apply-Bot
