### ISSUE TITLE
Not applying for jobs.

### ISSUE THREAD

**Issue by ria-debug** [nicolomantini/LinkedIn-Easy-Apply-Bot#90]
Hello. I installed and ran the code but it just opened linkedin, signed in and thats it. The execution ends there. It is not applying for jobs.
<img width="1046" alt="Screen Shot 2022-02-15 at 11 08 34 AM" src="https://user-images.githubusercontent.com/75501058/154101483-0d49ebbf-3beb-4258-9a67-d1ffa8c26fbc.png">

**Comment by cbroker1** [comment]
Hey @ria-debug I'm experiencing the exact same error. I even tried to reduce the .yaml file to see if that was the issue and no luck.
![image](https://user-images.githubusercontent.com/43118284/154120166-fb600859-bc5d-4cd8-9273-c205736dfaf3.png)

**Comment by cbroker1** [comment]
@ria-debug maybe we need to update the chrome driver version?

**Comment by cbroker1** [comment]
@ria-debug this is where I'm heading: https://github.com/NathanDuma/LinkedIn-Easy-Apply-Bot

**Comment by ria-debug** [comment]
@cbroker1 Did it work? the Nathan Duma one?
