### ISSUE TITLE
Not running 

### ISSUE THREAD

**Issue by simantstha** [nicolomantini/LinkedIn-Easy-Apply-Bot#92]
**Describe the bug**
When i try to run the file it gives me Assertion error
<img width="1069" alt="Screen Shot 2022-02-20 at 7 31 43 PM" src="https://user-images.githubusercontent.com/30699044/154871755-20aa2737-6a1b-41a8-abc5-f9decabe8d52.png">

**Desktop (please complete the following information):**
 - OS: MACOS
 - Browser Chrome
 - Version 98.0.4758.102

**Comment by imsantiagopoli** [comment]
[21792:21964:0427/222800.077:ERROR:util.cc(126)] Can't create base directory: C:\Program Files\Google\GoogleUpdater 

Do you know what does it mean?
