### ISSUE TITLE
Bot not applying to all the jobs

### ISSUE THREAD

**Issue by wasimekram** [nicolomantini/LinkedIn-Easy-Apply-Bot#93]
**Describe the bug**
The bot is not able to find the element job_title. It is able to apply to the first 2-3 jobs in each page.

**Screenshots**
If applicable, add screenshots of the LinkedIn page you are attempting to apply to. 

**Logs**
If applicable, attach your logs file found in `./logs/`

**Error Statement**
Error is as follows:
[errorlog.txt](https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/files/8458365/errorlog.txt)
If applicable and not stated above, provide the error statement you are receiving. 

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - 100

**Comment by faran678** [comment]
Remove the blacklist items if you have any. 

Keep the criteria to Username, password, positions, location. Always fixes the errors for me.
