### ISSUE TITLE
new issue 

### ISSUE THREAD

**Issue by kali786516** [nicolomantini/LinkedIn-Easy-Apply-Bot#94]
`
easyapplybot.py:103: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  user_field = self.browser.find_element_by_id("username")
easyapplybot.py:104: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  pw_field = self.browser.find_element_by_id("password")
easyapplybot.py:105: DeprecationWarning: find_element_by_css_selector is deprecated. Please use find_element(by=By.CSS_SELECTOR, value=css_selector) instead
  login_button = self.browser.find_element_by_css_selector(".btn__primary--large")
Traceback (most recent call last):
  File "easyapplybot.py", line 453, in <module>
    bot.start_apply(positions, locations)
  File "easyapplybot.py", line 122, in start_apply
    self.fill_data()
  File "easyapplybot.py", line 117, in fill_data
    self.browser.set_window_size(0, 0)
  File "webdriver.py", line 1387, in set_window_size
    self.set_window_rect(width=int(width), height=int(height))
  File "webdriver.py", line 1469, in set_window_rect
    raise InvalidArgumentException("x and y or height and width need values")
selenium.common.exceptions.InvalidArgumentException: Message: x and y or height and width need values

`

**Comment by mitch-zink** [comment]
I am having the same issue

**Comment by mrtknrt** [comment]
I have the same issue on mac
