### ISSUE TITLE
Message: no such element: Unable to locate element: {"method":"css selector","selector":".jobs-search-results"} 

### ISSUE THREAD

**Issue by faran678** [nicolomantini/LinkedIn-Easy-Apply-Bot#95]
**Describe the bug**
The bot logins to LinkedIn but never applies for jobs or even searches for the criteria not sure what is happening. 

I get the Error Message Below:
Message: no such element: Unable to locate element: {"method":"css selector","selector":".jobs-search-results"}   (Session info: chrome=102.0.5005.61)

Running the bot on Macbook 

**To Reproduce**
Just run the bot and it gives the error message and doesn't apply for jobs.

<img width="587" alt="Screen Shot 2022-05-31 at 7 21 02 PM" src="https://user-images.githubusercontent.com/44625575/171299369-1702d5bb-53f1-42b9-a9dd-a3fe9a260a96.png">

<img width="984" alt="Screen Shot 2022-05-31 at 7 22 20 PM" src="https://user-images.githubusercontent.com/44625575/171299490-f36084dd-d4a1-466a-950b-3819312b8a88.png">

**Comment by mrtknrt** [comment]
same issue
