### ISSUE TITLE
Code isn't running 

### ISSUE THREAD

**Issue by faran678** [nicolomantini/LinkedIn-Easy-Apply-Bot#96]
<img width="1439" alt="Screen Shot 2022-06-01 at 8 25 25 AM" src="https://user-images.githubusercontent.com/44625575/171404087-00b82519-1e15-456f-ae90-024e8fd0f140.png">
Does anyone know how I can get around this issue? I think it's something with Chromedriver I don't know how to fix it any thoughts?

**Comment by fernando-granco** [comment]
Change set_window_size(0, 0) to set_window_size(1, 1) and set_window_position(0, 0) to set_window_position(1, 1).

**Comment by faran678** [comment]
<img width="1439" alt="Screen Shot 2022-08-16 at 4 46 50 PM" src="https://user-images.githubusercontent.com/44625575/184982442-811b7eba-cf1c-4ca2-b7d0-4b7a9d80a6f3.png">

The code is running but only logs in does not apply for jobs. Any recommendation @fernando-granco

**Comment by ControlAltTea** [comment]
@faran678 I am having the same issue. Did you ever figure out what it was?
